name: build-actions
run-name: ${{ github.actor }} pushed and is building
on: 
  push:
    branches:
      - 'develop'
    tags:
      - 'v*'
jobs:
  build-release:
    if: startsWith(github.ref, 'refs/tags/')
    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest,windows-latest]
        sharedLib: 
        - {
          set: on,
          str: shared
          }  
        - {
          set: off,
          str: static
          }  
    runs-on: ${{ matrix.os }}


    steps:
          
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install dependencies on windows
        if: startsWith(matrix.os, 'windows')
        run: |
          choco install ninja cmake
          ninja --version
          cmake --version
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Install dependencies on ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build cmake
          ninja --version
          cmake --version
          gcc --version
          
      - name: Install dependencies on macos
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install cmake ninja
          ninja --version
          cmake --version

      - name: Create build directory
        run:  cmake -E make_directory ${{runner.temp}}/build


      - name: Configure
        working-directory: ${{ runner.temp }}/build
        run: cmake -G Ninja -DCMAKE_BUILD_TYPE="release" -DBUILD_TESTING=ON -DCMAKE_INSTALL_PREFIX="../install" -DBUILD_SHARED_LIBS=${{ matrix.sharedLib.set }} ${{ github.workspace }}

      - name: Build
        working-directory: ${{ runner.temp }}/build
        run: cmake --build .   

      - name: Test
        working-directory: ${{ runner.temp }}/build
        run: ninja test

      - name: Install
        working-directory: ${{ runner.temp }}/build
        run: cmake --install .

      - name: Binary Package
        working-directory: ${{ runner.temp }}/build
        run:  cpack -B packages --config CPackConfig.cmake


      - name: Release
        uses: softprops/action-gh-release@v1
        name: ${{ github.ref }}_${{ matrix.os }}_${{ matrix.sharedLib.str }}  
        with:
          files: ${{ runner.temp }}/build/packages/*.*

