name: build-actions
run-name: ${{ github.actor }} pushed and is building
on: 
  push:
    branches:
      - 'develop'
    tags:
      - 'v*'
jobs:
  build-release:
    if: startsWith(github.ref, 'refs/tags/')
    strategy:
      matrix:
        os: [ubuntu-latest]
        sharedLib: [on]
    runs-on: ${{ matrix.os }}


    steps:
          
      - uses: actions/checkout@v3
        with:
          ref: 'develop'
          fetch-depth: 0

      - if: ${{ startsWith(matrix.os, 'ubuntu') }} 
        name: Install Requirements
        run: sudo apt-get install -y build-essential ninja-build 
      
      - name: Create build directory
        run:  cmake -E make_directory ${{runner.temp}}/build


      - name: Configure
        working-directory: ${{ runner.temp }}/build
        run: cmake -G Ninja -DCMAKE_BUILD_TYPE="release" -DBUILD_TESTING=ON -DCMAKE_INSTALL_PREFIX="../install" -DBUILD_SHARED_LIBS=${{ matrix.sharedLib }} ${{ github.workspace }}

      - name: Build
        working-directory: ${{ runner.temp }}/build
        run: cmake --build .   

      - name: Test
        working-directory: ${{ runner.temp }}/build
        run: ninja test

      - name: Install
        working-directory: ${{ runner.temp }}/build
        run: cmake --install .

      - name: Binary Package
        working-directory: ${{ runner.temp }}/build
        run:  cpack -B packages --config CPackConfig.cmake

      - name: Source Package
        working-directory: ${{ runner.temp }}/build
        run: cpack -B packages --config CPackSourceConfig.cmake

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ runner.temp }}/build/packages/*.*

