name: build-actions
run-name: ${{ github.actor }} pushed and is building
on: 
  push:
    branches:
      - 'develop'
    tags:
    - '*'
jobs:
  build-release:
    strategy:
      matrix:
        os: [ubuntu-latest]
        sharedLib: [on,off]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'develop'

      - if: ${{ startsWith(matrix.os, 'ubuntu') }} 
        name: Install Requirements
        run: sudo apt-get install -y build-essential 
      
      - name: Create build directory
        run:  cmake -E make_directory ${{ runner.temp }}/build

      - name: Configure
        working-directory: ${{ runner.temp }}/build
        run: cmake -DCMAKE_BUILD_TYPE="release" -DANDROID=OFF -DWASM=OFF -DCMAKE_INSTALL_PREFIX="${{ runner.temp }}/install" -DBUILD_SHARED_LIBS=${{ matrix.sharedLib }} ${{ github.workspace }}

      - name: Build
        working-directory: ${{ runner.temp }}/build
        run: cmake --build .    

      - name: Install
        working-directory: ${{ runner.temp }}/build
        run: cmake --install .

      - name: Tar Release
        working-directory: ${{ runner.temp }}
        run:  cmake -E tar cvzf ${{ matrix.os }}-shared-${{ matrix.sharedLib }}.zip ${{ runner.temp }}/install/*

      - uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ runner.temp }}/${{ matrix.os }}-shared-${{ matrix.sharedLib }}.zip 

